# Usa la imagen de Node 18
FROM node:18

# Crea el directorio de la aplicación
WORKDIR /usr/src/app

# Instala las dependencias
COPY package*.json ./
RUN npm install

# Copia el código fuente
COPY . .

# Expone el puerto de la aplicación
EXPOSE 3000

# Comando para ejecutar la aplicación
CMD ["npx", "ts-node", "src/app.ts"]

